### ISSUE TITLE
[Dev] Blog missing good markup for social shares.

### ISSUE THREAD

**Issue by beriberikix** [yeoman/yeoman.io#145]
I saw I post on Google+ and noticed the blog is missing good markup - schema.org and otherwise. At the very least, the post title should be set so it gets SEO but a proper description would be nice for both Schema & Open Graph. This is what [Google sees](http://www.google.com/webmasters/tools/richsnippets?q=http%3A%2F%2Fyeoman.io%2Fblog%2Fgenerator-update-feb-0207.html) & what [Facebook sees](https://developers.facebook.com/tools/debug/og/object?q=http%3A%2F%2Fyeoman.io%2Fblog%2Fgenerator-update-feb-0207.html).

Using the [Google+ Snippet Tool](https://developers.google.com/+/web/snippet/), I generated this sample schema:
```
<!-- Update your html tag to include the itemscope and itemtype attributes. -->
<html itemscope itemtype="http://schema.org/Blog">

<!-- Add the following three tags inside head. -->
<meta itemprop="name" content="Updates to some of our generators">
<meta itemprop="description" content="Today we have a few updated generators for your consumption. nom nom nom. As always, we welcome any and all feedback or bug reports on the relevant trackers.">
<meta itemprop="image" content="http://i.imgur.com/hSEppjX.gif">
```

The same page has samples for FB.

**Comment by eddiemonge** [comment]
Seems done
