### ISSUE TITLE
[Docs] Extending Yeoman

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman.io#148]
Now that we support UIAdapters, we need to document the process.

* Wrapping Yeoman
  * How to wrap yeoman inside your own tools.
  * Basically, explain the concepts behind tools like `yo` and how authors can provide their own namespaces (`express init`, `sails init`, etc etc)
* Providing custom UI
  * UIAdapter interface requirements

**Comment by arthurvr** [comment]
> Should we aim to provide a demo 'wrapper' project that shows how this could be done?

Yeah, I believe a good example of this might make sense.

**Comment by SBoudrias** [comment]
I think `yo` is a good example project, we also have our test runner who's build on the same concept.

I'll close this issue as we're mostly done with this page in our documentation: http://yeoman.io/authoring/integrating-yeoman.html
