### ISSUE TITLE
[Docs] Remove yeoman/yeoman wiki

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/yeoman.io#190]
@eddiemonge said https://github.com/yeoman/yeoman/wiki can be removed, but I want to ensure we have everything correctly transferred over first.

Why is some of it in https://github.com/yeoman/yeoman.io/tree/master/app/docs and others in https://github.com/yeoman/yeoman.io/tree/master/app/wiki-archives ?

**Comment by supergray** [comment]
I think this issue can be closed.

**Comment by SBoudrias** [comment]
Yeah, it's done now. thanks
