### ISSUE TITLE
[Codelab] Workshop Feedback

### ISSUE THREAD

**Issue by pearlchen-old** [yeoman/yeoman.io#193]
Last night, I co-organized an in-person workshop to give people hands on experience with Yeoman by running through the codelab at their own pace. I'm opening up this issue to track any bugs and suggestions for the codelab from the mentors and attendees.

Bugs / Must-includes:
- [ ] TBD

Suggestions:
- [ ] TBD

**Comment by arthurvr** [comment]
> I guess those have to be installed separately. Not a big deal but thought i should mention that.

@ggomeze The codelab explicitly mentions `npm install --global yo bower grunt-cli`. Do you think there's anything more we can clarify?

> do you think its worth adding the git:// protocol workaround for networks where the port is blocked? or leave that as reading material from Bower itself?

Nah. That case is really rare and if it causes issues with Bower that's imho something to document on their side.
