### ISSUE TITLE
[Dev] Add Sticky sidebar

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman.io#233]
Itd be nice if the sidebar was sticky as some of the pages can get long

**Comment by piyushdwivedi** [comment]
The problem with a sticky side bar would be that there's going to be that extra space (which is initially taken by the page header) once the user starts scrolling down.  Like this - 
<img width="1301" alt="screen shot 2015-08-15 at 2 49 14 pm" src="https://cloud.githubusercontent.com/assets/3372659/9291000/fc69f1ee-435c-11e5-9f20-d12984f582c8.png">

**Comment by eddiemonge** [comment]
you mean at the top? we could have the top of the nav be higher. it doesnt have to be sticky in its current spot. it could scroll up with the page until it gets to its sticky spot

**Comment by piyushdwivedi** [comment]
@eddiemonge Cool. I'll take a crack at this. Do I need to assign this to myself while I'm working on it (just so someone else doesn't pick it up)? Sorry for silly questions. I'm just starting out as far as contributing to open source is concerned. :smile:

**Comment by SBoudrias** [comment]
> Do I need to assign this to myself while I'm working on it (just so someone else doesn't pick it up)?

We usually don't assign to people out of the core team as we receive a lot of "oh yeah, I'll send a PR" and never hear back.

I don't think anyone on the core team is currently working on improving the website, so we're safe assuming no one will pick up this feature :smile:

**Comment by piyushdwivedi** [comment]
I've got a fix for this. But, I can see my changes work only when I add the css to `.tmp/assets/css/main.css` and not when I add them in `app/assets/css/main.css`. Can someone tell me why this happens?

**Comment by eddiemonge** [comment]
You are running the `grunt serve` command right? Have you also run `npm update`?

**Comment by piyushdwivedi** [comment]
I was running `grunt serve:watch`. Running `npm update` and `grunt serve` did the trick I suppose. Will open up a PR today. :smiley:
