### ISSUE TITLE
Codelab Tutorial issue - bower_components installed in root, not app.

### ISSUE THREAD

**Issue by binkydog** [yeoman/yeoman.io#244]
Hello,

I've just walked through the yeoman tutorial (http://yeoman.io/codelab.html) and found it very useful (thanks!).  Overall it went pretty smoothly but I ran into  a couple snags due to the fact that bower_components apparently are now installed at project root (instead of in app) - at least that's how it installed for me.  (Note, I'm running on some newer versions - see end of post.)

First of all, **Step 8**, the karma.conf.js in the tutorial shows the files to load as:

```
files: [  
  'app/bower_components/jquery/jquery.js', ...
```

For which I had to change to:

```
files: [
  'bower_components/jquery/jquery.js',
```

no big deal.

---

Secondly, after using `grunt:serve` and `grunt:test` - which both worked fine - I got to **Step 10** and ran `grunt` and `grunt server:dist` which both ran without errors but I can see it's referring to the wrong place for bower_components.  For example, in the grunt output you see this:

```
concat:
  { generated: 
   { files: 
      [ { dest: '.tmp/concat/scripts/vendor.js',
          src: 
           [ 'app/bower_components/jquery/dist/jquery.js',
```

which basically results in the bower_components not getting included as well as the bootstrap css.  The end result when it runs looks like this:

![image](https://cloud.githubusercontent.com/assets/7891236/3318845/91257b5e-f71a-11e3-938a-0c0d4b564ebd.png)

This sounds like an issue with Yeoman, perhaps a grunt setting somewhere - not really sure how to fix it.  (Any suggestions would be appreciated...)

---

Running on Ubuntu 12.04. with:

node 0.10.4
npm 1.4.9
yo 1.1.2
bower 1.3.5
grunt-cli 0.1.13

I realize some of these are newer versions than your compatible ones...

Thanks

**Comment by alberto-f** [comment]
I'm still having this issue. A week ago using yeoman, installing angular, etc.

The grunt task: 

    wiredep: {
        app: {
        src: ['<%= yeoman.app %>/index.html'],
        ignorePath:  /\.\.\//
      }

When making grunt wiredep still getting issues. Bower_components folder is in parent directory and not in  /app folder. How can I solve this issue?

**Comment by eddiemonge** [comment]
Are you using the latest version? Because it works with that.

**Comment by alberto-f** [comment]
Yes it does if Im using __*grunt serve*__. Running __MAMP__ (in mac) for running the app still causes the same issue. It's fine using **_grunt serve_**. Just for curiosity... is this behavior expected? If so... it's a server configuration issue? It seems to me that it could be a setup server configuration...  **root directory** different when using **grunt serve** than when running in **MAMP**.

**Comment by eddiemonge** [comment]
Yes. This setup is designed to be used standalone. If you want to use a different server then it requires changing things. By using a different server, we are assuming that you have knowledge of what you are doing (or know how to google it) and can modify the setup to suit your needs. We can't test on every server since that is a completely unknown variable.

You most likely need to add a redirect in Apache to point `/bower_components` to the correct folder. should be a small change.

**Comment by VovaNazarenko** [comment]
Hi,
I was ruining tutorial and everything worked fine until step 9 and "grunt" command to build project
I run into following error:
```Running "autoprefixer:dist" (autoprefixer) taskAutoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() insteadFile .tmp/styles/main.css created.
jit-grunt: Plugin for the "ngtemplates" task not found.If you have installed the plugin already, please setting the static mapping.See https://github.com/shootaroo/jit-grunt#static-mappings
Warning: Task "ngtemplates" failed. Use --force to continue.
Aborted due to warnings.```
