### ISSUE TITLE
[Docs] Hackathon

### ISSUE THREAD

**Issue by ahmadnassri** [yeoman/yeoman.io#256]
Hey guys, 

we (@pearlchen + @ahmadnassri) are thinking of the viability of running a Yeoman Hackathon in Toronto as part of the [Yeoman Toronto group](http://www.yeoman.to), where developers can provide loving support in the form of: 

- tackling some bugs
- helping test & close Github tickets
- build new features & plugins for the rest of the world to use

The format would be something along the lines of:
- Intro to open-source contribution etiquette and github pull-request process. (for those unfamiliar)
- Guidelines from the maintainers (that's you!)
- Issue board / backlog grooming / picking group & assignment
- Split into groups and start tackling assigned tasks.

I'm not sure how big the open-source community is in the city, and how many people would be interested in donating their time to open-source projects, but I am highly optimistic :)

I'm also not certain to what degree would a group hacakathon in this format would be of value to the core development? or if any at all? the idea is to help the maintainers, not create more work for them!

love to get some feedback, thoughts, and if any similar experiment was done before, any key learnings?

cc: @sindresorhus @addyosmani

**Comment by SBoudrias** [comment]
I'll close this issue as we now have a dedicated repository.
