### ISSUE TITLE
Tutorial: recommending most recent version of npm

### ISSUE THREAD

**Issue by marc22alain** [yeoman/yeoman.io#354]
In trying to chase down various scaffolding issues occurring while testing the tutorial this week-end, it became clear that there are various intermittent errors that could be resolved by updating npm to v2+.

Issues with generator-angular are documented in this npm issue report:
https://github.com/npm/npm/issues/6238

The most current version of npm (2.1.5 at time of writing this) eliminated the npm error related to the tarball as well as the missing imagemin-related dependencies.

I suggest that the tutorial help the new users avoid these frustrating issues, by recommending they run
`$ npm install -g npm@next`
or
`$ npm install -g npm@2.1.5`
immediately after installing node.

**Comment by arthurvr** [comment]
#447
