### ISSUE TITLE
Replace talk on homepage

### ISSUE THREAD

**Issue by arthurvr** [yeoman/yeoman.io#414]
Currently on the homepage: 

> To learn more about the current developer tooling eco-system, you may be interested in watching Paul's talk on "Better Web App Development Through Tooling" or Addy's Yeoman session on Google Developers Live.

Where "Better Web App Development Through Tooling" is a talk by @paulirish from 2012. 

It must probably be replaced by something more recent. In general the content gets a little outdated, but worse is that the piece about yeoman gets outdated too. Tooling evolved so we shouldn't link to content from 2012. 

The best replacement for me seems http://addyosmani.com/blog/199-slides-on-front-end-tooling-workflows/, but better would be if there is a video recording. (cc: @addyosmani, is there?)

As always, I PR when it's decided.

**Comment by addyosmani** [comment]
I'm +1 on us trying to show only recent material, otherwise it's going to confuse beginners. My recent front-end tooling workflows talk wasn't recorded unfortunately, but I'm pretty sure folks in the community have talked about yo over the last few months and one of those might be worth picking up.

**Comment by arthurvr** [comment]
> but I'm pretty sure folks in the community have talked about yo over the last few months and one of those might be worth picking up.

The talk shouldn't be specific on yeoman right? The page says:

> To learn more about the current developer tooling eco-system, you may be interested in watching Paul's talk

**Comment by addyosmani** [comment]
Indeed. I don't think it needs to be 100% Yeoman focused at all.

**Comment by arthurvr** [comment]
Talking about removing outdated content, let's take a look at http://yeoman.io/learning/resources.html after this.

**Comment by hemanth** [comment]
We could add [this](http://d1xxv6tdqfm0z1.cloudfront.net/ygenerator.mp4) [tagtree thinge] to resources?

**Comment by arthurvr** [comment]
Still searching for a valuable replacement. Somebody an idea?

> We could add this [tagtree thinge] to resources?

+1

**Comment by SBoudrias** [comment]
@arthurvr If you feel that's a valuable replacement, then send a PR. It'll get people to react more promptly :)

If you're so so about it, maybe we should just remove the link to the 2012 talk for now?

**Comment by arthurvr** [comment]
>  If you feel that's a valuable replacement, then send a PR. It'll get people to react more promptly :)

@SBoudrias That's not a replacement for the talk on the homepage. We were talking about adding it to [resources](http://yeoman.io/learning/resources.html).

> If you're so so about it, maybe we should just remove the link to the 2012 talk for now?

I'm not so so about it, I just feel like it's weird we're advertising an outdated talk.

**Comment by SBoudrias** [comment]
I think the main question is: is the talk still relevant to the current yeoman workflow?

If it's not, then please send a PR removing it :)

**Comment by arthurvr** [comment]
> If it's not, then please send a PR removing it :)

Done :) #475
