### ISSUE TITLE
Improving the Menu on mobile screens 

### ISSUE THREAD

**Issue by ankurkaushal** [yeoman/yeoman.io#426]
I was just browsing [Yeoman](http://yeoman.io) on a mobile device and noticed that the menu can be improved quite a bit. For instance, it's kinda hard to differentiate between the Menu and Sub Menus. Just my two cents.

I am attaching a screenshot for reference as well. 

![screenshot](https://cloud.githubusercontent.com/assets/2236616/5905525/aa65b938-a55e-11e4-82c4-442a55101a8e.jpg)

**Comment by eddiemonge** [comment]
Updated a bit

![screenshot](https://cloud.githubusercontent.com/assets/127535/5968213/ef15d212-a7c9-11e4-84b1-524f203d7611.png)
