### ISSUE TITLE
Abstract away tool-specific commands under npm

### ISSUE THREAD

**Issue by silvenon** [yeoman/yeoman.io#427]
I'm not sure where to post this, but I think we could abstract away commands like `gulp serve`, `grunt serve`, `gulp` etc. as `npm` commands in `package.json`.

E. g. having `npm start` always firing up development environment is much more consistent and predictable. I'm not sure if there are any downsides to this.

**Comment by sindresorhus** [comment]
I like `npm` run scripts for simple things, but if you use gulp I prefer being explicit about it. It's also easier and shorter to type.

**Comment by eddiemonge** [comment]
> It's abstracting away the actual tools being used. It was that way to begin with but then there were problems. Let people use the tools that are being used directly. If they want to add the npm scripts they can anyway

**Comment by eddiemonge** [comment]
I think the consensus is we don't want to abstract away this much.

**Comment by silvenon** [comment]
Yep. Forgot to close.
