### ISSUE TITLE
TypeError: Cannot read property 'copyTpl' of undefined

### ISSUE THREAD

**Issue by alycda** [yeoman/yeoman.io#436]
Hi,

I was following along the tutorial [here](http://yeoman.io/authoring/file-system.html) when I ran into this error:

    /Users/adavis/Projects/generator-tcom/app/index.js:38
        this.fs.copyTpl(
                 ^
    TypeError: Cannot read property 'copyTpl' of undefined
        at module.exports.generators.NamedBase.extend.copyJSON (/Users/adavis/Projects/generator-tcom/app/index.js:38:12)
        at /Users/adavis/Projects/generator-tcom/node_modules/yeoman-generator/lib/base.js:395:14
        at processImmediate [as _immediateCallback] (timers.js:358:17)

**Generators expose all file methods on this.fs, which is an instance of mem-fs editor** which I've taken to mean that I do not need to put `var fs = require('fs')` at the top of my file, correct?

    var generators = require('yeoman-generator');
    module.exports = generators.NamedBase.extend({
      constructor: function() {
        generators.NamedBase.apply(this, arguments);
      },
      copyJSON: function() {
        this.fs.copyTpl(
          this.templatePath('app.json'),
          this.destinationPath('public/app.json'),
          { title: 'Templating with Yeoman' }
        );
      }
    });

I upgraded node & yeoman:

    $ npm -v
    2.5.1
    $ yo --version
    1.4.5
    $ node -v
    v0.12.0
    $ grunt -v
    grunt-cli: The grunt command line interface. (v0.1.13)

**Comment by SBoudrias** [comment]
1. you don't need to require `fs`, it's not the same thing
2. This will only work with `yeoman-generator` 0.18 - so update your package.json.

**Comment by alycda** [comment]
I ran `npm install --save yeoman-generator` before and after updating node & yeoman, I now have `0.18.9` but I'm still getting the error above.

    $ npm install --save yeoman-generator
    yeoman-generator@0.18.9 node_modules/yeoman-generator
    ├── read-chunk@1.0.1
    ├── dargs@3.0.1
    ├── detect-conflict@1.0.0
    ├── xdg-basedir@1.0.1
    ├── yeoman-assert@1.0.0
    ├── user-home@1.1.1
    ├── diff@1.2.2
    ├── class-extend@0.1.1
    ├── rimraf@2.2.8
    ├── text-table@0.2.0
    ├── mime@1.3.4
    ├── underscore.string@2.4.0
    ├── pretty-bytes@1.0.3 (get-stdin@4.0.1)
    ├── istextorbinary@1.0.2 (binaryextensions@1.0.0, textextensions@1.0.1)
    ├── async@0.9.0
    ├── debug@2.1.1 (ms@0.6.2)
    ├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
    ├── cross-spawn@0.2.6 (lru-cache@2.5.0)
    ├── nopt@3.0.1 (abbrev@1.0.5)
    ├── run-async@0.1.0 (once@1.3.1)
    ├── yeoman-welcome@1.0.1 (chalk@1.0.0)
    ├── mem-fs-editor@1.2.1 (vinyl@0.4.6)
    ├── mkdirp@0.5.0 (minimist@0.0.8)
    ├── shelljs@0.3.0
    ├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
    ├── cli-table@0.3.1 (colors@1.0.3)
    ├── dateformat@1.0.11 (get-stdin@4.0.1, meow@3.1.0)
    ├── github-username@1.1.1 (get-stdin@1.0.0, got@2.4.0)
    ├── glob@4.4.1 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
    ├── findup-sync@0.2.1 (glob@4.3.5)
    ├── file-utils@0.2.2 (isbinaryfile@2.0.3, minimatch@2.0.1, iconv-lite@0.4.7)
    ├── lodash@2.4.1
    ├── download@3.3.0 (get-stdin@3.0.2, each-async@1.1.1, gulp-rename@1.2.0, url-regex@2.1.2, download-status@2.1.1, vinyl@0.4.6, stream-combiner@0.2.1, ware@1.2.0, rc@0.5.5, meow@2.1.0, decompress-targz@2.1.0, concat-stream@1.4.7, decompress-unzip@2.1.2, decompress-tarbz2@2.0.2, decompress-tar@2.0.2, vinyl-fs@0.3.13, request@2.53.0)
    ├── gruntfile-editor@0.2.0 (ast-query@0.2.5)
    ├── sinon@1.12.2 (lolex@1.1.0, util@0.10.3, formatio@1.1.1)
    ├── cheerio@0.18.0 (entities@1.1.1, dom-serializer@0.0.1, CSSselect@0.4.1, htmlparser2@3.8.2)
    ├── yeoman-environment@1.2.4 (escape-string-regexp@1.0.3, untildify@2.0.0, globby@1.2.0, log-    symbols@1.0.2, mem-fs@1.1.0, grouped-queue@0.3.0, lodash@3.3.1)
    └── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.6,         readline2@0.1.1, rx@2.4.1, cli-color@0.3.2)

**Comment by SBoudrias** [comment]
Is your generator public?

**Comment by alycda** [comment]
no, I've only just started developing it locally.

**Comment by SBoudrias** [comment]
Well, publish it github and I'll have a look. But it definitively looks like a version issue on your side.
