### ISSUE TITLE
the newer yeoman version number should be '1.4.6'

### ISSUE THREAD

**Issue by exterry** [yeoman/yeoman.io#439]
In setup page (link: http://yeoman.io/codelab/setup.html)
at the bottom area the latest version number for yeoman is "1.4.6" but not "1.3.2"

**Comment by SBoudrias** [comment]
PR welcomed.

**Comment by eddiemonge** [comment]
And it has to be tested to make sure every step still works with that version

**Comment by arthurvr** [comment]
I will test this out this weekend.

**Comment by addyosmani** [comment]
@arthurvr did you have a chance to verify?

**Comment by arthurvr** [comment]
@addyosmani Using the latest bower, yo and grunt-cli it seems to work fine. Although the tutorial does not use the latest generator-angular and that feels kind of outdated. Anyways the version numbers we're talking about here can be updated.

**Comment by addyosmani** [comment]
Thanks for verifying @arthurvr. We might want to open an issue for tracking using the latest angular generator in case someone in the community has time to look at it.
