### ISSUE TITLE
grunt-wiredep ^1.7.0 fails when grunt serve

### ISSUE THREAD

**Issue by javierojeda94** [yeoman/yeoman.io#443]
When i ran `grunt serve` i had the followinf output

```
Running "serve" task

Running "clean:server" (clean) task

Running "wiredep:app" (wiredep) task
Warning: ENOENT, no such file or directory '/home/jojeda/web/mytodo/app/bower.json' Use --force to continue.

Aborted due to warnings.


Execution Time (2015-03-24 08:00:08 UTC)
loading tasks   14ms  ▇▇▇▇ 3%
serve            6ms  ▇▇ 1%
clean:server    17ms  ▇▇▇▇▇ 4%
wiredep:app    390ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 91%
Total 429ms
```
I managed to make it work by changing my package.json as follows:
* Previous
```json
"grunt-wiredep": "^1.7.0",
```
* My change
```json
"grunt-wiredep": "1.8.0",
```
Now everything looks fine and i could run `grunt serve` without problems.
I don't know if it is a problem with my pc. However it is a problem and it should be reported.
Thanks for reading!

**Comment by kevva** [comment]
This is the wrong repo. Report this issue on the correct generator repo.

**Comment by javierojeda94** [comment]
where do i find it?

**Comment by kevva** [comment]
I have no idea which generator you're running. What are you executing after `yo [...]`?

**Comment by javierojeda94** [comment]
it is angular, but i don't know if it is a problem with the generator or if it is specifically with grunt?

**Comment by kevva** [comment]
https://www.google.se/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=bower.json%20enoent%20wiredep
