### ISSUE TITLE
Copy directories not working

### ISSUE THREAD

**Issue by ykeijzer** [yeoman/yeoman.io#444]
just started using the amazing yeoman.io. Everything was working great, up until I tried to scaffold whole directores. Somehow, this.directory, this.bulkDirectory etc. aren't working. 
Inside the copyMainFiles function, I actually want to copy a complete directory with files to the specified locations. I'm not really looking forward to manually this.copy every file. (Console doesn't give any errors).

This is the index.js, I hope someone knows what goes wrong. Yeoman version: 1.4.6

 'use strict';
    var util = require('util');
    var path = require('path');
    var yeoman = require('yeoman-generator');
    var chalk = require('chalk');

var NulvijftigGenerator = yeoman.generators.Base.extend({
    promptUser: function() {
        var done = this.async();

        // have Yeoman greet the user
        console.log('asasd');

        var prompts = [{
            name: 'appName',
            message: 'Blablabla'
        }];

        this.prompt(prompts, function (props) {
            this.appName = props.appName;
            this.folderName = props.folderName;
            this.templateType = props.templateType;
            this.plugins = props.plugins;

            /* this.addDemoSection = props.addDemoSection; */

            done();
        }.bind(this));
    },
    scaffoldFolders: function(){

        // if the user selected basic webshop, create the required folders
        if(this.templateType == "extrawebshop"){
            // main folder (frontend value in configuration)
            this.mkdir(this.folderName);
            this.mkdir(this.folderName + "/account");
        }

        if(this.templateType == "basicwebsite"){
            // main folder (frontend value in configuration)
            this.mkdir(this.folderName);
        }
    },
    copyMainFiles: function(){

        // if the user selected basic webshop, copy the required files
        if(this.templateType == "basicwebsite"){
            this.directory("basicwebsite", this.folderName);
        }

        var context = {
            site_name: this.appName
        };

        //this.template("_header.html", "app/header.html", context);
    },
    runNpm: function(){
        var done = this.async();
        this.npmInstall("", function(){
            console.log("\nEverything Setup !!!\n");
            done();
        });
    }
});
module.exports = NulvijftigGenerator;

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)

**Comment by SBoudrias** [comment]
I don't know which documentation you read, but make sure the read the official one: http://yeoman.io/authoring/file-system.html
