### ISSUE TITLE
Confusing title description for international users

### ISSUE THREAD

**Issue by franciscop** [yeoman/yeoman.io#448]
When I discover yeoman and went to the website to see what it is, I was completely puzzled with the phrase:
> The web's scaffolding tool for modern webapps

A couple of guesses of why I think it's confusing for me:
- English is not my native language
- I am a self-taught programmer (though I have studied another Engineering).
- I didn't know what yeoman was before entering the page. I saw it mentioned with Grunt and Bower, and since I love these two I decided to investigate about how Yeoman might improve my workflow.

The main issue is the word *scaffold*, which I had to google. I think the title might also be misleading for other international users and that's why I am opening the issue.

Suggestion: make the wording easier for international users who might not be used to the word scaffolding or who arrive to the page with no prior knowledge of it. Maybe something as simple as this would work:

> The web's building tool for modern webapps

**Comment by pmarquez** [comment]
I can fully can agree with you that "Scafffolding" is not a common word, specially for us non -native speakers, but it so happens to be the correct word for the task. Maybe solve the problem with a link to a page explaining its meaning?

**Comment by sindresorhus** [comment]
I think we can expand on what scaffolding means in this context in the "What is Yeoman?" section, but I don't see us changing the tagline. And what you suggested as tagline incorrect. Yeoman is all about providing best practises for building modern webapps, which we do through our generators that scaffold out projects.

**Comment by eddiemonge** [comment]
Scaffolding is pretty common in programming. Most languages have some sort of scaffolding tool. The definition wikipedia gives is a pretty accurate one. We can take a look at clarifying in "What is Yeoman?" like Sindre said although I am not sure what else we can say in it to make it more clear.

**Comment by arthurvr** [comment]
I agree with Eddie. The tagline is pretty clear and "scaffolding" is pretty common. Looking at the "What is yeoman?" section I don't think there's much we can improve.
