### ISSUE TITLE
Make generators and sub-generators even more extenable with hooks

### ISSUE THREAD

**Issue by verrol** [yeoman/yeoman.io#451]
# Use Case Scenario:
Yeoman user Bob wants a script to be called with all the values provided sub-generator X:Y. Bob doesn't want this today and is not interested in learning how to write a sub-generator.

If there was a calling convention, where hooks are placed in the user's home directory or in the current project directory. Then a sub-generator could call the appropriate hook(s).

For example, the **jhipster:entity** sub-generator could be called after after the generator got all the user's input and ran, but before exiting.

Cross project hooks could be define in _~/.yo/hook/<generator-name>_, which would house scripts for both the generator and sub-generators. Per project hooks would be in _<project-dir>/.yo/hook/<generator-name>_. 
 
_~/.yo/jhipster/post.sh_   - run after '**$ yo jhipster**', passing any option given to the generator.
_~/.yo/jhipster/entity/post.sh_ - run after '**$ yo jhipser:entity <args>**', passing all command line args and answers to the script. It is the responsibility of the script.

# Specific Use Case:
Bob wants to generate a Solr collection schema .xml file based on the fields created for the entity. Each each entity will have a corresponding Solr schema file. Instead of parsing the generated file, Bob wants his script to get the same options the sub-generator got. In the specific case of **jhipster:entity**, Bob's script would simply use the entity name past to the sub-generator. Since **jhipster:entity** create a json file with all the meta data necessary to create or re-create the entity in _<project>/.jhipster/<entity>.json.

**Comment by SBoudrias** [comment]
What is the difference between learning to write a generator and learning a new hook system? There's the same level of complexity involved here. Plus, you'd end up modifying file using bash scripts? What about users on Windows?

What you want is to extend jhipster using our composability feature: http://yeoman.io/authoring/composability.html

There's also a couple other ways I can see to handling it:

- File watcher that react when specific files are changed/added
- Pre/Post commit hook that react in some way when some files are added/modified
