### ISSUE TITLE
Atom feed image urls are 404's

### ISSUE THREAD

**Issue by Munter** [yeoman/yeoman.io#453]
Looks like the URL's for images in the Atom feed are not pointing to the revved images:

```tap
not ok 121
  ---
    operator: error
    expected:
      
    actual:
      "Got 404 error retrieving http://yeoman.io/assets/img/blog/tasks.jpg\nIncluding assets:\n    inline Html in http://yeoman.io/blog/atom.xml\n"
    at: http://yeoman.io/assets/img/blog/tasks.jpg
  ...
not ok 122
  ---
    operator: error
    expected:
      
    actual:
      "Got 404 error retrieving http://yeoman.io/assets/img/blog/backbone-app-path.png\nIncluding assets:\n    inline Html in http://yeoman.io/blog/atom.xml\n"
    at: http://yeoman.io/assets/img/blog/backbone-app-path.png
  ...
not ok 123
  ---
    operator: error
    expected:
      
    actual:
      "Got 404 error retrieving http://yeoman.io/assets/img/blog/yo-backbone-mocha.png\nIncluding assets:\n    inline Html in http://yeoman.io/blog/atom.xml\n"
    at: http://yeoman.io/assets/img/blog/yo-backbone-mocha.png
  ...
```

**Comment by eddiemonge** [comment]
Not sure this is easily solvable: https://github.com/yeoman/grunt-usemin/issues/430

**Comment by Munter** [comment]
Solved here: https://github.com/yeoman/yeoman.io/compare/master...Munter:reduce?expand=1

**Comment by SBoudrias** [comment]
@Munter Mind sending a PR?

We already diverted from the base jekyll generator using jekyll 2. Plus the goal is to have a working product.

Feel free to maybe send a fix on generator-jekyll if you have the time.

**Comment by Munter** [comment]
I'm having trouble with my local ruby install, so I can't currently run all the tasks, which makes me less confident that this covers all bases. I'll see if I can get my setup in order so I don't introduce some crazy error with a PR

**Comment by arthurvr** [comment]
Was you ever able to fix your setup @Munter? We'd still appreciate a PR ;)

**Comment by Munter** [comment]
Oops. Forgot about this one. I just fixed my ruby setup now so I can at least run jekyll now.

I'm looking the whole thing over, and I really don't understand what all the sass compiling is doing in there. The project doesn't seem to use it. I'll clean everything out I thing is useless. Then at least it's easier to see if some workflow is not covered by tooling

**Comment by Munter** [comment]
There you go. Massive PR :)
