### ISSUE TITLE
Duplicate entry in list of top generator

### ISSUE THREAD

**Issue by zckrs** [yeoman/yeoman.io#466]
![image](https://cloud.githubusercontent.com/assets/3020368/7342576/798d8fc6-ecb6-11e4-9250-7fd3a7088cc6.png)

Someone have publish a copy of `generator-angular-fullstack` with different name.

https://www.npmjs.com/package/generator-angular-sparkstack

Is there a way to add it to `blacklist.json` ?

**Comment by sindresorhus** [comment]
Yeah, just add it to https://github.com/yeoman/yeoman.io/blob/master/app/blacklist.json

**Comment by zckrs** [comment]
Thank you ^^'
