### ISSUE TITLE
Two pages give totally different solution to npm permission error

### ISSUE THREAD

**Issue by hexchain** [yeoman/yeoman.io#470]
http://yeoman.io/codelab/setup.html "If you see permission or access errors, such as permission (`EPERM`) or access errors (`EACCESS`), do not use sudo as a work-around."
http://yeoman.io/codelab/install-generators.html "If you see permission or access errors, you will need to install the generator using sudo"

Personally I'd prefer the first solution as it's much cleaner, and (for linux) does not leave (package manager) untracked files in system.

**Comment by addyosmani** [comment]
> "If you see permission or access errors, such as permission (EPERM) or access errors (EACCESS), do not use sudo as a work-around."

I'm in favour of being consistent with this message and linking to https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by hexchain** [comment]
Linking to official docs is a good idea. But it seems to me that the [original solution](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) is still better-written than npm docs.

**Comment by SBoudrias** [comment]
Let's link to @sindresorhus guide. Mind sending a PR?

**Comment by hexchain** [comment]
> Let's link to @sindresorhus guide. Mind sending a PR?

Just remove the solution box on "Install generator" page. This page comes after "Setup" page, so if user encountered any problem during the first step, they may have followed the guide and fixed it already.

Is this okay? I'll send a PR on your greenlight.

**Comment by addyosmani** [comment]
> Let's link to @sindresorhus guide.

sgtm
