### ISSUE TITLE
tutorial - step one. grunt version

### ISSUE THREAD

**Issue by Vincenzovega** [yeoman/yeoman.io#480]
I get an error when using this command :8ball: 
command line: 
yo --version && bower --version && grunt --version

result: 
1.4.7
1.3.11
-bash: grunt: command not found

System macosx 10.10.3
node version: v0.12.4
Grunt version : grunt@0.4.5

**Comment by arthurvr** [comment]
```
npm install --global grunt-cli
```

As the tutorial states. Likely something went wrong with installing grunt-cli but that's not a yeoman problem.
