### ISSUE TITLE
Is the https://yeoman-generator-list.herokuapp.com open for external usage?

### ISSUE THREAD

**Issue by anstarovoyt** [yeoman/yeoman.io#483]
Hi. I am part of WebStorm team and now I am working on Yeoman integration. We are going to provide an access to list of yeoman generators from IDE and I want to use 'https://yeoman-generator-list.herokuapp.com' resource for loading generators information. Can I use it? I can create my own index of the packages but I think to use the same data source as 'yeoman.io' is a good idea.

**Comment by hemanth** [comment]
I think it should be fine, it's worth checking out [yeoman-generator-list](https://github.com/yeoman/yeoman-generator-list).

**Comment by hemanth** [comment]
Hope it helped.  :+1:

**Comment by anstarovoyt** [comment]
@hemanth thank you :)

**Comment by hemanth** [comment]
NP!
