### ISSUE TITLE
Error: Plugin for the "karma" task not found. when using tutorial

### ISSUE THREAD

**Issue by simonech** [yeoman/yeoman.io#490]
Been following the tutorial for the todo app.
I followed all steps in the tutorial, but then at step 8 I get this error

```
jit-grunt: Plugin for the "karma" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "karma" failed. Use --force to continue.
```

My versions are:
```
yo v1.4.7
bower  v1.4.1
grunt-cli v0.1.13
grunt v0.4.5
Karma version: 0.12.37
```

**Comment by eddiemonge** [comment]
Try updating to generator-angular 0.12.1 and see if that fixes it. Also, make sure you ran `npm install generator-karma` at some point.

**Comment by simonech** [comment]
Wasn't generator-karma supposed to be installed automatically as dipendency?






Sent from Windows Mail





From: Eddie Monge
Sent: ‎Tuesday‎, ‎7‎ ‎July‎ ‎2015 ‎21‎:‎50
To: yeoman/yeoman.io
Cc: Simone Chiaretta





Try updating to generator-angular 0.12.1 and see if that fixes it. Also, make sure you ran npm install generator-karma at some point.

**Comment by eddiemonge** [comment]
No. Its a peer-dependency and those aren't installed automatically anymore.

**Comment by simonech** [comment]
ok, that might explain then: it’s not mentioned in the tutorial that one has to install it.






Sent from Windows Mail





From: Eddie Monge
Sent: ‎Tuesday‎, ‎7‎ ‎July‎ ‎2015 ‎22‎:‎15
To: yeoman/yeoman.io
Cc: Simone Chiaretta





No. Its a peer-dependency and those aren't installed automatically anymore.

**Comment by simonech** [comment]
Could the problem also be that during the initial generation, at a certain point the process asks if it can overwrite package.json?






Sent from Windows Mail





From: Simone Chiaretta
Sent: ‎Tuesday‎, ‎7‎ ‎July‎ ‎2015 ‎22‎:‎17
To: yeoman/yeoman.io

**Comment by arthurvr** [comment]
> Could the problem also be that during the initial generation, at a certain point the process asks if it can overwrite package.json?

That's another known bug: https://github.com/yeoman/generator-angular/issues/1071. I don't think these are related though.

**Comment by simonech** [comment]
Actually I think they are:
if I just press the Enter key when it asks for overwriting, it installs
everything and it works.
If I type y or nothing it just stops at a certain point and karma and
phantom js do not get installed

On Tue, Jul 7, 2015 at 10:41 PM, Arthur Verschaeve <notifications@github.com
> wrote:

> Could the problem also be that during the initial generation, at a certain
> point the process asks if it can overwrite package.json?
>
> That's another known bug: yeoman/generator-angular#1071
> <https://github.com/yeoman/generator-angular/issues/1071>. I don't think
> these are related though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yeoman/yeoman.io/issues/490#issuecomment-119330135>.
>



-- 
Simone Chiaretta
Microsoft MVP ASP.NET - ASPInsider
Blog: http://codeclimber.net.nz
RSS: http://feeds2.feedburner.com/codeclimber
twitter: @simonech

**Comment by eddiemonge** [comment]
Closing this since that part is a known issue already.

**Comment by silvio-ai** [comment]
This is still a bug, as I've update the 'angular-generator', installed the 'generator-karma' and I'm still experiencing the same issue:
`
jit-grunt: Plugin for the "karma" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "karma" failed. Use --force to continue.

Aborted due to warnings.
`

**Comment by willhlaw** [comment]
Same issues here. Continue to get the same error even after installing the peerDep `generator-karma`.

**Comment by jesperpurola** [comment]
Same here

**Comment by leondeng** [comment]
Hi, guys, you should install karma anyways:
  npm install grunt-karma --save-dev

**Comment by raphapaulino** [comment]
I solved the problem following steps below:

1) npm install jit-grunt --save-dev
2) npm install karma-phantomjs-launcher --save-dev
3) npm install karma-jasmine --save-dev

or you can do it in one line:

$ npm install jit-grunt karma-phantomjs-launcher karma-jasmine --save-dev

After that, I build the app and test my dist folder:

$ grunt bulid (or just $ grunt)

It's worked for me

**Comment by ravinsinghd** [comment]
npm install grunt-karma --save-dev 

Solve my issue

**Comment by sergiolepore** [comment]
@ravinsinghd thank you very much, sir :smile:

**Comment by dinebennett** [comment]
@ravinsinghd - thanks, worked for me too :+1:

**Comment by shadiakiki1986** [comment]
@ravinsinghd - thanks, worked for me too

**Comment by shadiakiki1986** [comment]
@ravinsinghd - thanks, worked for me too :+1:

**Comment by wellington1993** [comment]
Thanks @ravinsinghd

**Comment by adiparwira** [comment]
thanks @ravinsinghd , worked for me too

**Comment by msjagadeesh** [comment]
hi  i run the grunt unit get in the error " Warning: Task "karma" not found. Use --force to continue."
