### ISSUE TITLE
Unquoted HTML attribute values

### ISSUE THREAD

**Issue by polybuildr** [yeoman/yeoman.io#491]
I happened to look at the yeoman.io source and noticed things like this:
```html
<a href=/contributing/style-guide.html>
```

Are the missing quotes around the attribute value intentional?

**Comment by arthurvr** [comment]
Yes. The minifier removes those to save some bytes and that's totally valid.

**Comment by polybuildr** [comment]
Hmm, I see. There are also some that aren't removed, though:
```html
<a href="http://yeoman.github.io/generator/">
```

Is there any particular reason for that?

**Comment by polybuildr** [comment]
Never mind. I notice it's only for URLs that have a starting `http`.
