### ISSUE TITLE
Add page about debugging a generator

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman.io#495]
We have documentation on how to debug a generator on yeoman-generator readme. This should probably go in our documentation on the website too.

**Comment by eddiemonge** [comment]
Fixed in:
* http://yeoman.io/authoring/debugging.html
* https://github.com/yeoman/yeoman.io/commit/581dec9d25dcd6a7a5546591c76a5034716af513
* https://github.com/yeoman/generator/commit/f3dcecf1628b5ec683d9dc2f89f32d88b7b9a7df

**Comment by SBoudrias** [comment]
awesome!!!

**Comment by arthurvr** [comment]
Yay!
