### ISSUE TITLE
no inTmpDir method in RunContext when executes helpers.run()

### ISSUE THREAD

**Issue by hlissnake** [yeoman/yeoman.io#497]
I found there is NO inTmpDir method in RunContext object when call helpers.run();
It always catch an error when I run Mocha commend order

**Comment by arthurvr** [comment]
This was introduced in https://github.com/yeoman/yeoman.io/commit/0e7539e5d1c92d597815c2e51b33e0feb833b586 - @SBoudrias Can you take a look?

**Comment by SBoudrias** [comment]
You're probably not using the latest version of `yeoman-generator`. Just update it to the latest and re-test.
