### ISSUE TITLE
Too many ordered list 

### ISSUE THREAD

**Issue by Gargaroz** [yeoman/yeoman.io#498]
In the [running-context page](http://yeoman.io/authoring/running-context.html) when the ways to create private methods are listed with an ordered list, the 3rd element appear as 1st of a new ordered list.

**Comment by arthurvr** [comment]
Ugh markdown. Does anybody know how to fix this (without just doing it in html)?

**Comment by SBoudrias** [comment]
Thanks @eddiemonge!
