### ISSUE TITLE
Find generators page is not loading on Chrome :(

### ISSUE THREAD

**Issue by carlinyuen** [yeoman/yeoman.io#502]
I tried refreshing a few times, no luck.

**Comment by lmatiolis** [comment]
Same problem here... It's returning 404.

`GET http://yeoman.io/assets/js/generators.js 404 (Not Found)`

**Comment by arthurvr** [comment]
Thanks for the report. It was broken since we moved some JavaScript around. Fixed, though it's a temporary fix till we land #500.

**Comment by arthurvr** [comment]
The deploy just run and it's fixed :)
