### ISSUE TITLE
Generators list does not load

### ISSUE THREAD

**Issue by adamzr** [yeoman/yeoman.io#504]
The error is
<code>
XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yeoman.io' is therefore not allowed access. The response had HTTP status code 503.
</code>
I use Chrome Version 44.0.2403.89 beta (64-bit) on a Mac

**Comment by arthurvr** [comment]
Thanks for the report. I am able to confirm this. We'll look into it. It has been going down every now and then. @SBoudrias Can you take a look? :)

**Comment by arthurvr** [comment]
Fixed :) Thanks again for the report.

**Comment by bostondevin** [comment]
I'm getting the same error today: 

XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yeoman.io' is therefore not allowed access. The response had HTTP status code 503.
