### ISSUE TITLE
Markdown links aren't showing up on the main site

### ISSUE THREAD

**Issue by cassidoo** [yeoman/yeoman.io#509]
The markdown in this file doesn't render correctly on the yeoman website.
https://github.com/yeoman/yeoman.io/blob/master/app/authoring/index.md

This is what it looks like on the site:
![image](https://cloud.githubusercontent.com/assets/1454517/9029864/6ba204a6-3968-11e5-8fd3-4a9d535fee8c.png)

**Comment by hemanth** [comment]
Suspects that `jekyll` is failing to convert `md` within `html`:

```html
<aside class="excerpt">

</aside>
```

**Comment by hemanth** [comment]
@cassidoo Thanks for reporting, it's [fixed](http://yeoman.io/authoring/)

**Comment by cassidoo** [comment]
awesome :+1:
