### ISSUE TITLE
yo just hangs. nothing happens  until....

### ISSUE THREAD

**Issue by kiev78** [yeoman/yeoman.io#525]
I installed everything in the startup guide http://yeoman.io/codelab/setup.html and http://yeoman.io/codelab/install-generators.html then yo asked me if i want to report my experience or something and i said yes, then it froze and nothing was happening. i restarted my command line. same thing... hangs.

until 5 min later it decided to say Allo.... can you put a little spinning icon or something to indicate it's loading?  it would be helpful.

*** Another issue I noticed is the mytodo app didn't reference the bootstrap css files for the project - so that's a problem I am not sure how to fix right now

**Comment by SBoudrias** [comment]
Can you open this issue on yeoman/yo repository.

This bug tracker is for the website.
