### ISSUE TITLE
"Discovering generators"'s generator list is down, returning 503 (https://yeoman-generator-list.herokuapp.com/)

### ISSUE THREAD

**Issue by benjaminma** [yeoman/yeoman.io#528]
http://yeoman.io/generators/

https://yeoman-generator-list.herokuapp.com/ (503 Service Unavailable)

Is it more appropriate to submit the issue to: https://github.com/yeoman/yeoman-generator-list?

**Comment by eddiemonge** [comment]
We know. I'm working on making it better. Either repo is fine.
