### ISSUE TITLE
The sticky menu goes to the right once we scroll

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman.io#530]
The menu change position as we scroll down the page.

It starts off at the right of the content, and it stays centered with the website.

But then, as soon as we scroll and the menu enter it's sticky mode, it ends up sticking to the rightmost part of our browser screen.

**Comment by eddiemonge** [comment]
Ah. On wider screens the menu is positioned absolutely and due to relative positioning on the parent, it has a bit of padding. when it changes to fixed, it no longer stays in the parent. Fixable. I'll try to get to it today
