### ISSUE TITLE
The list of generators fails to load

### ISSUE THREAD

**Issue by daniel** [yeoman/yeoman.io#531]
The page http://yeoman.io/generators/ gets stuck on "Loading generators..." (in both Google Chrome and Safari).

I get this error in the Chrome javascript console:
`XMLHttpRequest cannot load https://yeoman-generator-list.herokuapp.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://yeoman.io' is therefore not allowed access. The response had HTTP status code 503.`

**Comment by eddiemonge** [comment]
Thanks. It comes and goes and we are working on keeping it more stable.
