### ISSUE TITLE
"Discovering generators" page is broken

### ISSUE THREAD

**Issue by dennisjac** [yeoman/yeoman.io#532]
When I go to the "Discovering generators" page all I get is "Loading generators...". After a few seconds the following error appears in the console:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://yeoman-generator-list.herokuapp.com/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by ruyadorno** [comment]
thanks @dennisjac, it has been reported already #531
