### ISSUE TITLE
Angular app is not loaded as in the tutorial (CSS problem?)

### ISSUE THREAD

**Issue by do-n-khanh** [yeoman/yeoman.io#534]
Hi,

I follow exactly the tutorial up to  http://yeoman.io/codelab/preview-inbrowser.html

This is what I get 
![9](https://cloud.githubusercontent.com/assets/3012507/9768793/fa252a3a-5760-11e5-9884-cf4aa650870d.JPG)

I tried to install yo angular many times, but could not fix the error.
Please help.

**Comment by eddiemonge** [comment]
This is correct. It looks like bootstrap isn't loading properly, which was fixed but now might need a new fix depending on bootstrap. Check the issues at https://github.com/yeoman/generator-angular
