### ISSUE TITLE
get CLI arguments

### ISSUE THREAD

**Issue by tykayn** [yeoman/yeoman.io#536]
i am writing my own generator angular-jeej 
but i dont find how to use arguments in command line. for example "yo angular-jeej:controller myarg1 myarg2" 
i dont find a doc to retrieve the myarg1 and 2 in the index.js 
i expected to find it in the doc about context, but i searched everywhere on the yeoman.io site and can't get any clue.
https://github.com/yeoman/yeoman.io/blob/master/app/authoring/running-context.md

something like having the arguments as a helper object in the prompting function would be great.
```
module.exports = yeoman.generators.Base.extend({
prompting : function(arguments){
if(arguments.has('myarg1')){
// ... do stuff if myarg1 is met, etc
}
//...
}})
```

**Comment by SBoudrias** [comment]
Please ask any future support questions on StackOverflow.

You'll find your answer on this documentation page http://yeoman.io/authoring/user-interactions.html
