### ISSUE TITLE
A little more detail in "Writing Your Own Generator" for those of us who are new to Node.js

### ISSUE THREAD

**Issue by nrvale0** [yeoman/yeoman.io#660]
The docs "Writing Your Own Generator" would benefit by having some additional information for those who are new to Node.js:
1. When discussing extending the base generator the docs does not call out that the code should be placed in the index.js file under generators/app.
2. It would be nice if just before the attempt to run the generator after linking the entirety of the source code in index.js was shown in the article. From previous code snippets one might be led to believe that the code should include the definition for _only_ method1 and method2 and not also the constructor definition from the previous paragraphs.

**Comment by addyosmani** [comment]
Thanks for the feedback!
