### ISSUE TITLE
Missing full API documentation for yeoman-test

### ISSUE THREAD

**Issue by Autre31415** [yeoman/yeoman.io#771]
On http://yeoman.io/authoring/testing.html there is a link to check out the full API for yeoman-test helpers. That link leads to the [yeoman-test github repo](https://github.com/yeoman/yeoman-test) which does not have API documentation and instead has a link of its own that leads back to the testing page on yeoman.io.

There is also an issue about this API documentation circle of links on yeoman-test https://github.com/yeoman/yeoman-test/issues/34 which was posted around 10 months ago.

It seems that the full API documentation is locked behind the almighty infinite loop of doom.

**Comment by gangwarily** [comment]
I know this issue has been opened for some while but I noticed that the link for the full API documentation for creating a custom generator is missing from yeoman.io. Clicking on the "Full API documentation" takes the user to a dead link.

**Comment by camilleb** [comment]
Is there an another way to see the full API documentation?

**Comment by gangwarily** [comment]
I've looked all over the place and haven't found a way to access the full API docs.

**Comment by SBoudrias** [comment]
The API is generated in a gh-page here: https://github.com/yeoman/generator/tree/gh-pages

Looks like Github changed how the gh-pages works... I'm not sure why the link stopped working. If you want to help, this would be very useful.

Originally `yeoman.github.io/generator` would point to the repo gh-page.

**Comment by farant** [comment]
Also missing documentation for `yeoman-environment`
![screen shot 2019-02-13 at 10 42 50 am](https://user-images.githubusercontent.com/14899475/52724017-942df200-2f7c-11e9-8852-7f91619f1bea.png)
https://yeoman.io/environment/ shows a "Not Found" page
