### ISSUE TITLE
The fountainjs.io link in the codelab tutorials is leading to a malware page

### ISSUE THREAD

**Issue by sjdeak** [yeoman/yeoman.io#788]
codelab page: https://yeoman.io/codelab/keep-going.html

![image](https://user-images.githubusercontent.com/8575264/53299797-6dc05e80-387a-11e9-9d8a-f460ab759b12.png)

The malware page spies itself to be flash update page. 

![image](https://user-images.githubusercontent.com/8575264/53299826-a102ed80-387a-11e9-8466-0391757aee2d.png)

When you try to install that update package, some software will be installed on your machine. What's worse is that your browser will be hijacked, the default search engine and new tab page will all be set to weknow.ac, and i can't set them back. 😢

![image](https://user-images.githubusercontent.com/8575264/53299886-52098800-387b-11e9-8efd-d8608ca0ac6c.png)

Maybe we should remove that link now.

**Comment by mischah** [comment]
Thanks for letting us know. 

And yes, the link should be removed. The fountain generators seem to unmaintained for quite while.

So this link should be removed. The sooner the better. 

Do you like to create a PR?

**Comment by SBoudrias** [comment]
I made a global search and replace all links to this website. Thanks for reporting!

**Comment by sjdeak** [comment]
My pleasure 😄
