### ISSUE TITLE
Website seems outdated

### ISSUE THREAD

**Issue by IObert** [yeoman/yeoman.io#818]
Hi,

I recently wanted to upgrade my generator [easy-ui5](https://www.npmjs.com/package/generator-easy-ui5) to version 5.X. Unfortunately, I got some error when upgrading to 5.x: the function `installDependencies()` is not available any longer. I had a look at the release notes of [yeoman/generator](https://github.com/yeoman/generator/releases) and it seems that this action in indeed gone. 
The problem is that I'm not able to find any information about this. The [official page](https://yeoman.io/authoring/dependencies.html#combined-use) still promotes this function and the [API doc](https://yeoman.github.io/generator/) also seems to be "stuck" on version 4.13.

Can you please update the page or refer me to the current API doc?
![Screenshot 2021-03-26 at 10 15 29](https://user-images.githubusercontent.com/1873245/112609744-32f3d080-8e1c-11eb-9a3d-f1335bae8a33.png)

**Comment by mischah** [comment]
Oops. Thanks for the info.
I’ve just updated the API docs: https://yeoman.github.io/generator/

I'm going to update the website as well :octocat:
