### ISSUE TITLE
Issue in the Navbar (header) of the application

### ISSUE THREAD

**Issue by him-raw99** [yeoman/yeoman.io#828]
<img width="729" alt="image" src="https://github.com/yeoman/yeoman.io/assets/97152850/86a3aa08-e488-4e5b-89c3-c854d9586a06">

# The position of logo is falling outside the navbar or header (according to your code base) is it on purpose?

### If not, I am confident I can fix this. kindly assign this issue to me

**Comment by eddiemonge** [comment]
Its on purpose as a style design. Thank you for the offer though.
